apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: demo
          image: image_url
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: credvolume
              mounthPath: /etc/creds
              readOnly: true
          volumes:
            - name: credvolume
              secretName: db-secrets
