apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example_app
spec:
  containers:
    - name: demo
      image: image_url
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthy
          port: 3000
        initialDelaySeconds: 15
        timeoutSeconds: 30